import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import MobileSidebar from "@/components/layout/MobileSidebar";
import Image from "next/image";
import BG from "../../public/bg.png";
import { Button } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-darkBrown`}>
        <Navbar />
        <MobileSidebar/>
        <div className="z-10 bg-[url('/bg.png')] bg-fixed">{children}</div>

      </body>
    </html>
  );
}
